### ISSUE TITLE
Add platform_configurations section to README

### ISSUE THREAD

**Issue by gwbrown** [fizzed/stork#21]
It took me quite a while to figure out how to specify a user and group for the generated systemd service file in the stork.yml launcher definition.  I eventually found it in one of the example files, but it doesn't appear to be documented anywhere.

Here's the example I found, but I don't know if this is all of the available options for this section:

```
platform_configurations:
  LINUX:
    daemon_method: NOHUP
    user: "daemon"
    group: "daemon"
  
  MAC_OSX:
    user: "_daemon"
    group: "_daemon"
  
  WINDOWS:
    daemon_method: JSLWIN
```
